=== subhannita1994/UMLet-Refactoring/DRAM OADymPPaC/examples/oadymppac.dtd
<!-- 
  Copyright (c) 2001
  Ecole des Mines de Nantes, INRIA, IRISA, Universite d'Orleans, Cosytec, Ilog

  $Id: oadymppac.dtd,v 1.14 2002/01/22 23:47:58 fekete Exp $

  DTD describing traces for constraint based programs.
  Project OADYMPPAC.  All the documentation related to the project can
  be found at the folloging URL:
  http://contraintes.inria.fr/OADymPPaC/

  Copyright (c) 2001 OADymPPaC Project (Ecole des Mines de Nantes,
  INRIA, IRISA, Universite d'Orleans, ILOG, Cosytec).

  For the OADymPPaC version 1.0:

  Namespace:
    http://contraintes.inria.fr/OADymPPaC

  Public identifier:
    PUBLIC "-//OADYMPPAC//DTD OADYMPPAC 1.0//EN"

  URI for the DTD:
    http://contraintes.inria.fr/OADymPPaC/oadymppac10.dtd
--> 

<!ENTITY % Toplevel
  "(new-variable | new-constraint | reduce | restore | wake-up |
    suspend | true | reject | activate | select-constraint | 
    select-update | tell | deactivate | solution | new-annotation |
    new-stage | start-stage | end-stage |
    suspend-stage | resume-stage | stage )*" >

<!ELEMENT oadymppac %Toplevel; >
<!ATTLIST oadymppac
   xmlns CDATA #FIXED "http://contraintes.inria.fr/OADymPPaC">

<!ENTITY % integer "CDATA" >

<!ENTITY % constraintAttributes
  "cname IDREF #IMPLIED
   externalrep CDATA #IMPLIED
   internalrep CDATA #IMPLIED" >

<!ENTITY % eventAttributes
  "depth %integer; #IMPLIED
   n %integer; #IMPLIED
   time %integer; #IMPLIED
   context CDATA #IMPLIED
   activities IDREFS #IMPLIED" >

<!ENTITY % commonAttributes
  "%eventAttributes;
   %constraintAttributes;" >

<!ENTITY % valueList "( values | range )*" >

<!ELEMENT new-variable %valueList; >
<!ATTLIST new-variable
  %eventAttributes;
  vname ID #REQUIRED
  type (int | rat | real | enum | string ) "int"
  externalrep CDATA #IMPLIED
  internalrep CDATA #IMPLIED >

<!ELEMENT new-constraint (update)* >
<!ATTLIST new-constraint
  %eventAttributes;
  cname ID #REQUIRED
  orig ( user | system ) #IMPLIED
  externalrep CDATA #IMPLIED
  internalrep CDATA #IMPLIED >

<!ELEMENT reduce ( state?, (update)*, explanation? ) >
<!ATTLIST reduce
  %commonAttributes; >

<!ELEMENT restore ( state?, (update)* ) >
<!ATTLIST restore
  %commonAttributes; >

<!ELEMENT wake-up (state?, (cause)* ) >
<!ATTLIST wake-up
  %commonAttributes; >

<!ELEMENT suspend (state?) >
<!ATTLIST suspend
  %commonAttributes; >

<!ELEMENT true (state?) >
<!ATTLIST true
  %commonAttributes; >

<!ELEMENT reject ( state?, explanation?) >
<!ATTLIST reject
  %commonAttributes; >

<!ELEMENT select-constraint ( state?) >
<!ATTLIST select-constraint
  %commonAttributes; >

<!ELEMENT select-update ( state? , %valueList; ) >
<!ATTLIST select-update
  %eventAttributes;
  vname IDREF #REQUIRED
  type (ground | any | min | max | minmax |
  empty | val | nothing) #REQUIRED >

<!ELEMENT activate (state?, explanation?) >
<!ATTLIST activate
  %commonAttributes; >

<!ELEMENT tell (state?) >
<!ATTLIST tell
   depth %integer; #REQUIRED
   n %integer; #IMPLIED
   time %integer; #IMPLIED
   context CDATA #IMPLIED
   activities IDREFS #IMPLIED
   %constraintAttributes; >

<!ELEMENT deactivate (state?) >
<!ATTLIST deactivate
  %commonAttributes; >

<!ELEMENT solution (state?) >
<!ATTLIST solution
  val %integer; #IMPLIED
  %commonAttributes; >

<!-- Annotations may replace stages -->
<!ELEMENT new-annotation (#PCDATA) >
<!ATTLIST new-annotation
  id ID #REQUIRED
  type IDREF #IMPLIED
  name CDATA #IMPLIED
  refs IDREFS #IMPLIED >

<!ELEMENT new-stage (#PCDATA) >
<!ATTLIST new-stage
  id ID #REQUIRED 
  sname CDATA #IMPLIED
  refs IDREFS #IMPLIED >
<!-- such as "labeling", "init" -->

<!ENTITY % StageAttributes
  "sname IDREF #REQUIRED
   refs IDREFS #IMPLIED
   detail CDATA #IMPLIED" >

<!ELEMENT stage %Toplevel; >
<!ATTLIST stage
  %StageAttributes; >

<!ELEMENT start-stage EMPTY >
<!ATTLIST start-stage
  %StageAttributes; >

<!ELEMENT suspend-stage EMPTY >
<!ATTLIST suspend-stage
  %StageAttributes; >

<!ELEMENT resume-stage EMPTY >
<!ATTLIST resume-stage
  %StageAttributes; >

<!ELEMENT end-stage EMPTY >
<!ATTLIST end-stage
  %StageAttributes; >

<!ELEMENT values (#PCDATA) >

<!ELEMENT range EMPTY>
<!ATTLIST range
  from CDATA #REQUIRED
  to CDATA #REQUIRED >

<!ELEMENT vardomain %valueList; >
<!ATTLIST vardomain
  vname IDREF #REQUIRED >

<!ELEMENT state (alist?, slist?, qlist?, tlist?, rlist?, ulist?, vlist?, (misc)*) >
<!ATTLIST state
  precision (changed | full) #IMPLIED >

<!ELEMENT alist (constraint)* >
<!ELEMENT slist (constraint)* >
<!ELEMENT qlist (constraint)* >
<!ELEMENT tlist (constraint)* >
<!ELEMENT rlist (constraint)* >
<!ELEMENT ulist (update)* >
<!ELEMENT vlist (vardomain)* >
<!ELEMENT misc (#PCDATA) >
<!ATTLIST misc
  type CDATA #IMPLIED >

<!ELEMENT constraint EMPTY>
<!ATTLIST constraint
  cname IDREF #REQUIRED >

<!ELEMENT update %valueList; >
<!ATTLIST update
  cname IDREF #IMPLIED
  vname IDREF #REQUIRED
  type (ground | any | min | max | minmax | empty | val | nothing) #IMPLIED >

<!ELEMENT cause %valueList; >
<!ATTLIST cause
  cname IDREF #IMPLIED
  vname IDREF #REQUIRED
  type (ground | any | min | max | minmax | empty | val) #IMPLIED >


<!ELEMENT explanation ((cause)*, (constraint)*) >

=== subhannita1994/UMLet-Refactoring/DRAM OADymPPaC/examples/oatrace.xml
<!DOCTYPE oadymppac SYSTEM "oadymppac.dtd">
<oadymppac>
<new-constraint n="1" cname="c0" externalrep="control constraint"/>
  <new-variable n="2" vname="a">
      <values> 1 2 3 4</values>
  </new-variable>
  <new-variable n="3" vname="b">
      <values> 1 2 3 4</values>
  </new-variable>
  <new-variable n="4" vname="c">
      <values> 1 2 3 4</values>
  </new-variable>
 <new-constraint n="5" cname="c1" externalrep="e-allDifferent((a:[4](1, 2, 3, 4), b:[4](1, 2, 3, 4), c:[4](1, 2, 3, 4)))">
   <update vname="a" type="val" />
   <update vname="a" type="max" />
   <update vname="a" type="min" />
   <update vname="b" type="val" />
   <update vname="b" type="max" />
   <update vname="b" type="min" />
   <update vname="c" type="val" />
   <update vname="c" type="max" />
   <update vname="c" type="min" />
 </new-constraint>
 <activate n="6" cname="c1" />
 <suspend n="7" cname="c1" />
 <select-constraint n="8" cname="c1" />
 <new-constraint n="9" cname="c2" externalrep="a = 1">
   <update vname="a" type="val" />
   <update vname="a" type="max" />
   <update vname="a" type="min" />
 </new-constraint>
 <activate n="10" cname="c2" />
 <suspend n="11" cname="c2" />
 <select-constraint n="12" cname="c2" />
 <reduce n="13" cname="c2">
   <update vname="a" type="val"> <values>2</values></update>
   <explanation>
      <constraint cname="c2"/>
   </explanation>
 </reduce>
 <reduce n="14" cname="c2">
   <update vname="a" type="val"> <values>3</values></update>
   <explanation>
      <constraint cname="c2"/>
   </explanation>
 </reduce>
 <reduce n="15" cname="c2">
   <update vname="a" type="val"> <values>4</values></update>
   <explanation>
      <constraint cname="c2"/>
   </explanation>
 </reduce>
 <select-update n="16" vname="a" type="val"/>
 <wake-up n="17" cname="c1">
   <update vname="a" type="val" />
 </wake-up>
 <wake-up n="18" cname="c1">
   <update vname="a" type="val" />
 </wake-up>
 <wake-up n="19" cname="c1">
   <update vname="a" type="val" />
 </wake-up>
 <reduce n="20" cname="c1">
   <update vname="b" type="val"> <values>1</values></update>
   <explanation>
      <constraint cname="c1"/>
      <constraint cname="c2"/>
   </explanation>
 </reduce>
 <reduce n="21" cname="c1">
   <update vname="c" type="val"> <values>1</values></update>
   <explanation>
      <constraint cname="c1"/>
      <constraint cname="c2"/>
   </explanation>
 </reduce>
 <select-update n="22" vname="b" type="val"/>
 <select-update n="23" vname="c" type="val"/>
 <new-constraint n="24" cname="c3" externalrep="b = 2">
   <update vname="b" type="val" />
   <update vname="b" type="max" />
   <update vname="b" type="min" />
 </new-constraint>
 <activate n="25" cname="c3" />
 <suspend n="26" cname="c3" />
 <select-constraint n="27" cname="c3" />
 <reduce n="28" cname="c3">
   <update vname="b" type="val"> <values>3</values></update>
   <explanation>
      <constraint cname="c3"/>
   </explanation>
 </reduce>
 <reduce n="29" cname="c3">
   <update vname="b" type="val"> <values>4</values></update>
   <explanation>
      <constraint cname="c3"/>
   </explanation>
 </reduce>
 <select-update n="30" vname="b" type="val"/>
 <wake-up n="31" cname="c1">
   <update vname="b" type="val" />
 </wake-up>
 <wake-up n="32" cname="c1">
   <update vname="b" type="val" />
 </wake-up>
 <reduce n="33" cname="c1">
   <update vname="c" type="val"> <values>2</values></update>
   <explanation>
      <constraint cname="c1"/>
      <constraint cname="c2"/>
      <constraint cname="c3"/>
   </explanation>
 </reduce>
 <select-update n="34" vname="c" type="val"/>
 <new-constraint n="35" cname="c4" externalrep="c = 3">
   <update vname="c" type="val" />
   <update vname="c" type="max" />
   <update vname="c" type="min" />
 </new-constraint>
 <activate n="36" cname="c4" />
 <suspend n="37" cname="c4" />
 <select-constraint n="38" cname="c4" />
 <reduce n="39" cname="c4">
   <update vname="c" type="val"> <values>4</values></update>
   <explanation>
      <constraint cname="c4"/>
   </explanation>
 </reduce>
 <select-update n="40" vname="c" type="val"/>
 <wake-up n="41" cname="c1">
   <update vname="c" type="val" />
 </wake-up>
 <solution n="42" />
  <new-variable n="43" vname="*dummy*">
     <range from='0' to='1' />
  </new-variable>
 <reduce n="44" cname="c1">
   <update vname="*dummy*" type="max"> <values>2</values></update>
   <explanation>
      <constraint cname="c2"/>
      <constraint cname="c3"/>
      <constraint cname="c4"/>
   </explanation>
 </reduce>
 <reject n="45" cname="c1" />
 <deactivate n="46" cname="c4" />
 <restore n="47">
   <update vname="c" type="val"> <values>4</values></update>
 </restore>
 <restore n="48">
   <update vname="*dummy*" type="min"> <values>0</values></update>
 </restore>
 <select-update n="49" vname="c" type="val"/>
 <select-update n="50" vname="*dummy*" type="min"/>
 <new-constraint n="51" cname="c5" externalrep="c !== 3">
   <update vname="c" type="val" />
   <update vname="c" type="max" />
   <update vname="c" type="min" />
 </new-constraint>
 <activate n="52" cname="c5" />
 <suspend n="53" cname="c5" />
 <select-constraint n="54" cname="c5" />
 <reduce n="55" cname="c5">
   <update vname="c" type="val"> <values>3</values></update>
   <explanation>
      <constraint cname="c2"/>
      <constraint cname="c3"/>
   </explanation>
 </reduce>
 <select-update n="56" vname="c" type="val"/>
 <wake-up n="57" cname="c1">
   <update vname="c" type="val" />
 </wake-up>
 <solution n="58" />
 <reduce n="59" cname="c1">
   <update vname="*dummy*" type="max"> <values>2</values></update>
   <explanation>
      <constraint cname="c2"/>
      <constraint cname="c3"/>
   </explanation>
 </reduce>
 <reject n="60" cname="c1" />
 <deactivate n="61" cname="c3" />
 <restore n="62">
   <update vname="b" type="val"> <values>3</values></update>
 </restore>
 <restore n="63">
   <update vname="b" type="val"> <values>4</values></update>
 </restore>
 <restore n="64">
   <update vname="c" type="val"> <values>2</values></update>
 </restore>
 <restore n="65">
   <update vname="c" type="val"> <values>3</values></update>
 </restore>
 <restore n="66">
   <update vname="*dummy*" type="min"> <values>0</values></update>
 </restore>
 <select-update n="67" vname="b" type="val"/>
 <select-update n="68" vname="c" type="val"/>
 <select-update n="69" vname="*dummy*" type="min"/>
 <new-constraint n="70" cname="c6" externalrep="b !== 2">
   <update vname="b" type="val" />
   <update vname="b" type="max" />
   <update vname="b" type="min" />
 </new-constraint>
 <activate n="71" cname="c6" />
 <suspend n="72" cname="c6" />
 <select-constraint n="73" cname="c6" />
 <reduce n="74" cname="c6">
   <update vname="b" type="val"> <values>2</values></update>
   <explanation>
      <constraint cname="c2"/>
   </explanation>
 </reduce>
 <select-update n="75" vname="b" type="val"/>
 <wake-up n="76" cname="c1">
   <update vname="b" type="val" />
 </wake-up>
 <new-constraint n="77" cname="c7" externalrep="b = 3">
   <update vname="b" type="val" />
   <update vname="b" type="max" />
   <update vname="b" type="min" />
 </new-constraint>
 <activate n="78" cname="c7" />
 <suspend n="79" cname="c7" />
 <select-constraint n="80" cname="c7" />
 <reduce n="81" cname="c7">
   <update vname="b" type="val"> <values>4</values></update>
   <explanation>
      <constraint cname="c7"/>
   </explanation>
 </reduce>
 <select-update n="82" vname="b" type="val"/>
 <wake-up n="83" cname="c1">
   <update vname="b" type="val" />
 </wake-up>
 <wake-up n="84" cname="c6">
   <update vname="b" type="val" />
 </wake-up>
 <reduce n="85" cname="c6">
   <update vname="c" type="val"> <values>3</values></update>
   <explanation>
      <constraint cname="c1"/>
      <constraint cname="c2"/>
      <constraint cname="c7"/>
   </explanation>
 </reduce>
 <select-update n="86" vname="c" type="val"/>
 <new-constraint n="87" cname="c8" externalrep="c = 2">
   <update vname="c" type="val" />
   <update vname="c" type="max" />
   <update vname="c" type="min" />
 </new-constraint>
 <activate n="88" cname="c8" />
 <suspend n="89" cname="c8" />
 <select-constraint n="90" cname="c8" />
 <reduce n="91" cname="c8">
   <update vname="c" type="val"> <values>4</values></update>
   <explanation>
      <constraint cname="c8"/>
   </explanation>
 </reduce>
 <select-update n="92" vname="c" type="val"/>
 <wake-up n="93" cname="c1">
   <update vname="c" type="val" />
 </wake-up>
 <solution n="94" />
 <reduce n="95" cname="c1">
   <update vname="*dummy*" type="max"> <values>2</values></update>
   <explanation>
      <constraint cname="c2"/>
      <constraint cname="c7"/>
      <constraint cname="c8"/>
   </explanation>
 </reduce>
 <reject n="96" cname="c1" />
 <deactivate n="97" cname="c8" />
 <restore n="98">
   <update vname="c" type="val"> <values>4</values></update>
 </restore>
 <restore n="99">
   <update vname="*dummy*" type="min"> <values>0</values></update>
 </restore>
 <select-update n="100" vname="c" type="val"/>
 <select-update n="101" vname="*dummy*" type="min"/>
 <new-constraint n="102" cname="c9" externalrep="c !== 2">
   <update vname="c" type="val" />
   <update vname="c" type="max" />
   <update vname="c" type="min" />
 </new-constraint>
 <activate n="103" cname="c9" />
 <suspend n="104" cname="c9" />
 <select-constraint n="105" cname="c9" />
 <reduce n="106" cname="c9">
   <update vname="c" type="val"> <values>2</values></update>
   <explanation>
      <constraint cname="c2"/>
      <constraint cname="c7"/>
   </explanation>
 </reduce>
 <select-update n="107" vname="c" type="val"/>
 <wake-up n="108" cname="c1">
   <update vname="c" type="val" />
 </wake-up>
 <solution n="109" />
 <reduce n="110" cname="c1">
   <update vname="*dummy*" type="max"> <values>2</values></update>
   <explanation>
      <constraint cname="c2"/>
      <constraint cname="c7"/>
   </explanation>
 </reduce>
 <reject n="111" cname="c1" />
 <deactivate n="112" cname="c7" />
 <restore n="113">
   <update vname="b" type="val"> <values>4</values></update>
 </restore>
